### ISSUE TITLE
Re-running Wagyu on its own output sometimes makes additional changes

### ISSUE THREAD

**Issue by ericfischer** [mapbox/wagyu#60]
`tests/geometry-test-data/input-polyjson/croatia1.json` is an uncleaned border polygon for Croatia at z0, the one that Tippecanoe calls Wagyu to clean when you run

    grep Croatia tests/border/in.json | ./tippecanoe -z1 --detect-shared-borders -f -o foo.mbtiles

If you run Wagyu on this polygon:

    ./fixture-tester -t union -f positive tests/geometry-test-data/input-polyjson/croatia1.json

you get the cleaned polygon in `tests/geometry-test-data/input-polyjson/croatia2.json`. However, if you rerun Wagyu on that second polygon:

    ./fixture-tester -t union -f positive tests/geometry-test-data/input-polyjson/croatia2.json

you get a third polygon, the one in `tests/geometry-test-data/input-polyjson/croatia3.json`. If you run Wagyu again on the third polygon, it is stable and you get an identical polygon back.

I had expected that giving Wagyu a strictly simple polygon that was previously the output of Wagyu would return the identical polygon rather than making additional changes to it.

**Comment by ericfischer** [comment]
It looks like the first-stage output may actually have some overlapping rings:

![screen shot 2017-01-03 at 4 20 41 pm](https://cloud.githubusercontent.com/assets/1951835/21627968/a4fb7bfe-d1d0-11e6-8076-7f3574d467e6.png)

but `./tests/run-geometry-tests.sh ./fixture-tester` does not complain.

**Comment by ericfischer** [comment]
It looks like `fixture-tester` only guarantees that each outer ring of a MultiPolygon is valid with respect to its inner rings, not that the outer rings are free from conflict with each other.

**Comment by flippmoke** [comment]
This has been really hard to test properly due to #34 but it is something I have been concerned about! Good find!

**Comment by ericfischer** [comment]
Thanks. I just made a PR (https://github.com/mapbox/wagyu/pull/61) to test for stability (after putting the rings in a canonical order) that I hope will help track down some other similar problems.

**Comment by ericfischer** [comment]
The stability test finds 1105 of 3120 outputs to be unstable, which is far more than the 105 that `boost::is_valid` complains about, so instability is not necessarily an indicator of invalidity.

**Comment by springmeyer** [comment]
Stability seems like a critical issue - thanks for raising this @ericfischer and for adding a test harness for it. What are the next steps to getting wagyu to have stable output the first run?

**Comment by flippmoke** [comment]
In order to really pursue this with vigor we would need to have #34 properly sorted so that we can actually debug properly with out have all the false negatives. I would also be curious how many of these differences are simply due to a change in the initial position of the ring of a polygon. So we might have a large number of "stability" issues that aren't really anything more then the order of the points.

**Comment by ericfischer** [comment]
@flippmoke I did already make my test code normalize the order of points within each ring, so these are case where it changes in some other way.

**Comment by springmeyer** [comment]
> In order to really pursue this with vigor we would need to have #34 properly sorted so that we can actually debug properly with out have all the false negatives. 

Hrm, this feels important to de-couple from #34 and possible boost bugs. Why not write our own function to determine validity and stability?

**Comment by flippmoke** [comment]
> Why not write our own function to determine validity and stability?
@springmeyer I have considered such a think already, but this could be a big undertaking I am afraid.

**Comment by springmeyer** [comment]
@flippmoke - wagyu internally already has code to detect self intersections. What more would be required past that? What makes it a big undertaking?

**Comment by flippmoke** [comment]
@springmeyer we have code to detect where rings meet at the same point, not any code that actually does intersection testing against different segments. Additionally the code within Wagyu might not be ideal to port to an algorithm such as this (although the knowledge from writing Wagyu would help in writing the validity algorithm). 

This is its own algorithm in some aspect, which is why I have always trusted the boost geometry, because up until this point it was always very good.

**Comment by flippmoke** [comment]
I dug into some of the results of these tests and they have to do with two seperate situations:

The first is a situation where the snap rounding when repeated multiple times will result in more snapping then originally occurs. This results in features changing in shapes over time due to this, and unless we ran snap rounding until it stabilized it will continue to be this way. However, our current limited use of snap rounding preserves the original shapes of rings in a better fashion IMO. Therefore, it is likely a speed savings and a good technical reason not to expect stable results when repeatedly running Wagyu.

<img width="290" alt="screen shot 2017-02-08 at 4 05 07 pm" src="https://cloud.githubusercontent.com/assets/1794907/22801094/1d63090a-eed1-11e6-95cc-4fde8e3e941c.png">

Additionally, there are sometimes additional points that are kept during processing of wagyu that are collinear in nature. This occurs in the output because it is possible that other rings or vectors might touch these points and these points are important to keep because currently the validity results will throw due to rounding errors in a false manner at these points. During a repeated run, the situation where these are not touching is removed. We could consider this as a possible feature to add to the topology correction portion of wagyu, however, I do not view it as something that is urgent to fix as it might degrade performance. 

<img width="270" alt="screen shot 2017-02-08 at 4 02 27 pm" src="https://cloud.githubusercontent.com/assets/1794907/22801002/cfdc7d6a-eed0-11e6-8a8c-56f1559db6ad.png">
